name: application

outputs:
  - run.vcd
  - tiles_Tile_PE.list
  - tiles_Tile_MemCore.list

commands:
  - ./pe_dse_run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  app_array_width: 8
  app_array_height: 8
  pipeline_config_interval: 8
  interconnect_only: False
  soc_only: False
  PWR_AWARE: False
  use_container: True
  use_local_garnet: True
  app_to_run: "tests/conv_3_3"
  dse_pe: "lassen"
  waves: False

postconditions:
  - assert File( 'outputs/run.vcd' )
