#=========================================================================
# Custom Genus Scripts
#=========================================================================

name: custom-dc-scripts

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
    - compile-options.tcl
    - generate-results.tcl
